name: installipfs
description: install kubo

runs:
  using: "composite"
  steps:
    - name: Install kubo
      shell: bash
      run: (cd /tmp && go install github.com/ipfs/kubo/cmd/ipfs@v0.16.0-rc1)
